services:
  nginx:
    image: nginx:latest
    container_name: hmp-nginx
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - "443:443"
    depends_on:
      - api

  api:
    build: .
    container_name: hmp-api
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: hmp-postgres
    env_file: .env
