services:
  nginx:
    image: nginx:latest
    container_name: hmp-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  api:
    build: .
    container_name: hmp-api
